### ISSUE TITLE
Can't make it work on Catalina (10.15.6)

### ISSUE THREAD

**Issue by ach94er** [vahe-evoyan/armenian-phonetic#14]
First things first, thank you for the hope to have decent Armenian Keyboard on Mac!

Though I have the dmg file manually copied to the Keyboard Layouts folder and restarted the machine a couple of times and still I do not see any of mentioned layouts available on input sources.

Let me know what is the additional info you need.

**Comment by khanzadyan** [comment]
Just found the way to do this under Catalina. You would need to follow the instruction in https://github.com/vahe-evoyan/armenian-phonetic#manual-install and 

1. copy the `ArmenianPhonetic.icns` and `ArmenianPhonetic.bundle` to your `~/username/Library/Keyboard Layouts` directory. 
2. Open system Preferences > Keyboard > Input Sources and press `+` to add new keyboard layout.
3. Find the Armenian section and you will see the newly added layout there. Select it and you are good.

**Comment by ach94er** [comment]
Thanks a lot, it worked after update to Big Sur :) I believe back then I tried out the manual install, but didn't copy all files needed.
