### ISSUE TITLE
Why not just copy the whole bundle?

### ISSUE THREAD

**Issue by sssilver** [vahe-evoyan/armenian-phonetic#2]
The documentation specifies that .icns and .keylayout files be cherry picked and copied into /Library/Keyboard\ Layouts, why not just copy the .bundle directly?

**Comment by vahe-evoyan** [comment]
@sssilver right, the documentation is a bit outdated :( The up-to date version is posted on [my blog](https://evoyan.org/armenian-phonetic-for-mac/). Will update it soon :)

**Comment by vahe-evoyan** [comment]
The DMG installer is available with [v2.0](https://github.com/vahe-evoyan/armenian-phonetic/releases/tag/v2.0) and the Readme updated accordingly.
