### ISSUE TITLE
The icon is invisible on a dark menu bar

### ISSUE THREAD

**Issue by sssilver** [vahe-evoyan/armenian-phonetic#7]
When the configuration option "Use dark menu bar and Dock" is checked on System Preferences/General, the black/white icon of the keyboard layout becomes effectively invisible.

The icon needs to be redrawn in different colors to accommodate for the dark menu bar.

**Comment by pogossian** [comment]
I have a same issue. But I think that the problem isn't in icon, because it was taken from native icon file`(/System/Library/Keyboard\ Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat)`

**Comment by dnavre** [comment]
Same here :)
<img width="89" alt="screen shot 2018-08-25 at 4 00 19 pm" src="https://user-images.githubusercontent.com/341914/44618058-12d48d00-a880-11e8-875e-42015f021cae.png">
<img width="75" alt="screen shot 2018-08-25 at 4 00 28 pm" src="https://user-images.githubusercontent.com/341914/44618059-136d2380-a880-11e8-953e-e158eaed2f4c.png">

**Comment by vahe-evoyan** [comment]
Hey there, I've struggle with this icon pretty much already. Can't figure out how the PNG channels should be organized in order to make the automatic coloring work. Decided to go with Armenian flags, like in the previous versions of the native layouts.
